In [ ]:
class company:
  a="shares"
  b="funds"

class emp(company):
  c="id"

In [ ]:
swaraj=company()
aditya=emp()

In [ ]:
aditya.c

'id'

In [ ]:
aditya.a

'shares'

In [ ]:
# Basic Hybrid Inheritance Example

class A:
    def method_a(self):
        print("Method from class A")

class B(A):
    def method_b(self):
        print("Method from class B")

class C(A):
    def method_c(self):
        print("Method from class C")

class D(B, C):
    def method_d(self):
        print("Method from class D")

# Create an instance of class D and call methods from all parent classes
d_instance = D()
d_instance.method_a()
d_instance.method_b()
d_instance.method_c()
d_instance.method_d()

Method from class A
Method from class B
Method from class C
Method from class D

In [ ]:
from os import name
class dadaji:
  def __init__(self,name):
    self.name=name

  def property(self):
    print("dadaji property")

class papaji:
  def work(self):
    print("I am working")

class child(dadaji):
  def play(self):
    print("I am playing")

In [ ]:
#Multiple Inheritance - Python
class wholesaler:
  def whole(self):
    print("I am a wholesaler")

class retailer:
  def retail(self):
    print("I am a retailer")

class distributor(wholesaler,retailer):
  def distributor(self):
    print("I am a distributor")

In [ ]:
omkar=retailer()

In [ ]:
omkar.retail()

I am a retailer

In [ ]:
tejas=wholesaler()

In [ ]:
tejas.whole()

I am a wholesaler

In [ ]:
#Hierachial Inheritance - Python
class Milk:
  def milk(self):
    print("I am a milk product")

class cheese(Milk):
  def cheese(self):
    print("I am a cheese product")

class butter(Milk):
  def butter(self):
    print("I am a butter product")

class curd(Milk):
  def curd(self):
    print("I am a curd product")

In [ ]:
amul= Milk()

In [ ]:
amul.milk()

I am a milk product

In [ ]:
#create a function [91-8484078886,91-8888218168]
#["nitin","aloo"]---f(x)-->1 p and len is 5
#extract table from website and create a dict like {"India":91,"Greece":30...}

In [ ]:
names = ["Raj","Parshva","Mansi","Arpita","Tejal","Tejas","Gitesh","Hannah",
    "Bob",
    "Nan",
    "Elle",
    "Malayalam","Ashish","Neha","Yash"]

In [ ]:
palindrome_names = [
    "Ada",
    "Anna",
    "Eve",
    "Otto",
    "Hannah",
    "Bob",
    "Nan",
    "Elle",
    "Malayalam",
    "Nitin",
    "Anina",
    "Aviva",
    "Mom",
    "Noon",
    "Dad"
]

In [ ]:
def pal(palindrome_names):
  for s in palindrome_names:
    if s==s[::-1]:
      return True
    else:
      return False

In [ ]:
pal("ana")

True

In [ ]:
import re

def is_valid_phone_number_with_country_code(phone_number):
    """
    Checks if a phone number has a country code and is in a valid format.

    Args:
        phone_number: The phone number string to validate.

    Returns:
        True if the phone number is valid, False otherwise.
    """
    # Regular expression to match country code (1-3 digits) followed by a hyphen
    # and then a phone number (7-15 digits)
    pattern = re.compile(r'^\d{1,3}-\d{7,15}$')

    if pattern.match(phone_number):
        return True
    else:
        return False

# Example usage:
print(is_valid_phone_number_with_country_code("91-8484078886"))
print(is_valid_phone_number_with_country_code("1-555-1234567"))
print(is_valid_phone_number_with_country_code("8484078886")) # Missing country code
print(is_valid_phone_number_with_country_code("91-123")) # Too short

True
False
False
False

In [ ]:
import pandas as pd
data=pd.read_html("https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes")
print(data)

[    ISO 3166[1] name[5]                       Official state name[6][a]  \
    ISO 3166[1] name[5]                       Official state name[6][a]
0           Afghanistan          the Islamic Republic of Afghanistan[b]
1         Åland Islands                                     Åland[c][d]
2               Albania                         the Republic of Albania
3               Algeria     the People's Democratic Republic of Algeria
4        American Samoa                               American Samoa[c]
..                  ...                                             ...
266   Wallis and Futuna  the Territory of the Wallis and Futuna Islands
267  Western Sahara[an]      the Sahrawi Arab Democratic Republic[c][d]
268               Yemen                           the Republic of Yemen
269              Zambia                          the Republic of Zambia
270            Zimbabwe                        the Republic of Zimbabwe

    Sovereignty [6][7][8] ISO 3166-1[2]                   \
    Sovereignty [6][7][8]       A-2 [5] A-3 [5] Num. [5]
0               UN member            AF     AFG      004
1                 Finland            AX     ALA      248
2               UN member            AL     ALB      008
3               UN member            DZ     DZA      012
4           United States            AS     ASM      016
..                    ...           ...     ...      ...
266                France            WF     WLF      876
267          Disputed[ao]            EH     ESH      732
268             UN member            YE     YEM      887
269             UN member            ZM     ZMB      894
270             UN member            ZW     ZWE      716

    ISO 3166-2[3] subdivision codes link TLD [9]
    ISO 3166-2[3] subdivision codes link TLD [9]
0                          ISO 3166-2:AF     .af
1                          ISO 3166-2:AX     .ax
2                          ISO 3166-2:AL     .al
3                          ISO 3166-2:DZ     .dz
4                          ISO 3166-2:AS     .as
..                                   ...     ...
266                        ISO 3166-2:WF     .wf
267                        ISO 3166-2:EH    [ap]
268                        ISO 3166-2:YE     .ye
269                        ISO 3166-2:ZM     .zm
270                        ISO 3166-2:ZW     .zw

[271 rows x 8 columns],   vteISO 3166 – codes for the representation of names of countries and their subdivisions  \
0                     List of ISO 3166 country codes
1                         ISO 3166-1 – country codes
2             ISO 3166-2 – country subdivision codes
3  AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX A...
4                                            deleted
5   ISO 3166-3 – codes for former names of countries
6                a changed from TP b changed from YU

  vteISO 3166 – codes for the representation of names of countries and their subdivisions.1
0                     List of ISO 3166 country codes
1                            alpha-2 alpha-3 numeric
2  AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX A...
3  AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX A...
4                                             AN CSb
5                                               List
6                a changed from TP b changed from YU                                         ,                                                    0  \
0  AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX A...
1                                            deleted

                                                   1
0  AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX A...
1                                             AN CSb  ,      vteGeocode systems                               vteGeocode systems.1
0  Administrative codes  FIPS country code (FIPS 10-4) FIPS place code ...
1         Airport codes                IATA airport code ICAO airport code
2         Country codes  IANA country code ISO 3166-1 alpha-2 alpha-3 n...
3  Geodesic place codes  Global C-squares Geohash Geohash-36 GEOREF Int...
4                Global  C-squares Geohash Geohash-36 GEOREF Internatio...
5              Regional  ICES Statistical Rectangles (north-east Atlant...
6          Postal codes  Australian post codes CEP (Brazil) Eircodes (R...
7             Telephony  ITU-R country codes ITU-T country calling code...
8         Amateur radio  Maidenhead Locator System Historical : QRA loc...,           0                                                  1
0    Global  C-squares Geohash Geohash-36 GEOREF Internatio...
1  Regional  ICES Statistical Rectangles (north-east Atlant...]

In [ ]:
df=pd.DataFrame(data[0])
print(data)

[    ISO 3166[1] name[5]                       Official state name[6][a]  \
    ISO 3166[1] name[5]                       Official state name[6][a]
0           Afghanistan          the Islamic Republic of Afghanistan[b]
1         Åland Islands                                     Åland[c][d]
2               Albania                         the Republic of Albania
3               Algeria     the People's Democratic Republic of Algeria
4        American Samoa                               American Samoa[c]
..                  ...                                             ...
266   Wallis and Futuna  the Territory of the Wallis and Futuna Islands
267  Western Sahara[an]      the Sahrawi Arab Democratic Republic[c][d]
268               Yemen                           the Republic of Yemen
269              Zambia                          the Republic of Zambia
270            Zimbabwe                        the Republic of Zimbabwe

    Sovereignty [6][7][8] ISO 3166-1[2]                   \
    Sovereignty [6][7][8]       A-2 [5] A-3 [5] Num. [5]
0               UN member            AF     AFG      004
1                 Finland            AX     ALA      248
2               UN member            AL     ALB      008
3               UN member            DZ     DZA      012
4           United States            AS     ASM      016
..                    ...           ...     ...      ...
266                France            WF     WLF      876
267          Disputed[ao]            EH     ESH      732
268             UN member            YE     YEM      887
269             UN member            ZM     ZMB      894
270             UN member            ZW     ZWE      716

    ISO 3166-2[3] subdivision codes link TLD [9]
    ISO 3166-2[3] subdivision codes link TLD [9]
0                          ISO 3166-2:AF     .af
1                          ISO 3166-2:AX     .ax
2                          ISO 3166-2:AL     .al
3                          ISO 3166-2:DZ     .dz
4                          ISO 3166-2:AS     .as
..                                   ...     ...
266                        ISO 3166-2:WF     .wf
267                        ISO 3166-2:EH    [ap]
268                        ISO 3166-2:YE     .ye
269                        ISO 3166-2:ZM     .zm
270                        ISO 3166-2:ZW     .zw

[271 rows x 8 columns],   vteISO 3166 – codes for the representation of names of countries and their subdivisions  \
0                     List of ISO 3166 country codes
1                         ISO 3166-1 – country codes
2             ISO 3166-2 – country subdivision codes
3  AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX A...
4                                            deleted
5   ISO 3166-3 – codes for former names of countries
6                a changed from TP b changed from YU

  vteISO 3166 – codes for the representation of names of countries and their subdivisions.1
0                     List of ISO 3166 country codes
1                            alpha-2 alpha-3 numeric
2  AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX A...
3  AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX A...
4                                             AN CSb
5                                               List
6                a changed from TP b changed from YU                                         ,                                                    0  \
0  AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX A...
1                                            deleted

                                                   1
0  AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX A...
1                                             AN CSb  ,      vteGeocode systems                               vteGeocode systems.1
0  Administrative codes  FIPS country code (FIPS 10-4) FIPS place code ...
1         Airport codes                IATA airport code ICAO airport code
2         Country codes  IANA country code ISO 3166-1 alpha-2 alpha-3 n...
3  Geodesic place codes  Global C-squares Geohash Geohash-36 GEOREF Int...
4                Global  C-squares Geohash Geohash-36 GEOREF Internatio...
5              Regional  ICES Statistical Rectangles (north-east Atlant...
6          Postal codes  Australian post codes CEP (Brazil) Eircodes (R...
7             Telephony  ITU-R country codes ITU-T country calling code...
8         Amateur radio  Maidenhead Locator System Historical : QRA loc...,           0                                                  1
0    Global  C-squares Geohash Geohash-36 GEOREF Internatio...
1  Regional  ICES Statistical Rectangles (north-east Atlant...]

In [ ]:
df.head()

  ISO 3166[1] name[5]                    Official state name[6][a]  \
  ISO 3166[1] name[5]                    Official state name[6][a]
0         Afghanistan       the Islamic Republic of Afghanistan[b]
1       Åland Islands                                  Åland[c][d]
2             Albania                      the Republic of Albania
3             Algeria  the People's Democratic Republic of Algeria
4      American Samoa                            American Samoa[c]

  Sovereignty [6][7][8] ISO 3166-1[2]                   \
  Sovereignty [6][7][8]       A-2 [5] A-3 [5] Num. [5]
0             UN member            AF     AFG      004
1               Finland            AX     ALA      248
2             UN member            AL     ALB      008
3             UN member            DZ     DZA      012
4         United States            AS     ASM      016

  ISO 3166-2[3] subdivision codes link TLD [9]
  ISO 3166-2[3] subdivision codes link TLD [9]
0                        ISO 3166-2:AF     .af
1                        ISO 3166-2:AX     .ax
2                        ISO 3166-2:AL     .al
3                        ISO 3166-2:DZ     .dz
4                        ISO 3166-2:AS     .as

In [ ]:
print(df.info)

<bound method DataFrame.info of     ISO 3166[1] name[5]                       Official state name[6][a]  \
    ISO 3166[1] name[5]                       Official state name[6][a]
0           Afghanistan          the Islamic Republic of Afghanistan[b]
1         Åland Islands                                     Åland[c][d]
2               Albania                         the Republic of Albania
3               Algeria     the People's Democratic Republic of Algeria
4        American Samoa                               American Samoa[c]
..                  ...                                             ...
266   Wallis and Futuna  the Territory of the Wallis and Futuna Islands
267  Western Sahara[an]      the Sahrawi Arab Democratic Republic[c][d]
268               Yemen                           the Republic of Yemen
269              Zambia                          the Republic of Zambia
270            Zimbabwe                        the Republic of Zimbabwe

    Sovereignty [6][7][8] ISO 3166-1[2]                   \
    Sovereignty [6][7][8]       A-2 [5] A-3 [5] Num. [5]
0               UN member            AF     AFG      004
1                 Finland            AX     ALA      248
2               UN member            AL     ALB      008
3               UN member            DZ     DZA      012
4           United States            AS     ASM      016
..                    ...           ...     ...      ...
266                France            WF     WLF      876
267          Disputed[ao]            EH     ESH      732
268             UN member            YE     YEM      887
269             UN member            ZM     ZMB      894
270             UN member            ZW     ZWE      716

    ISO 3166-2[3] subdivision codes link TLD [9]
    ISO 3166-2[3] subdivision codes link TLD [9]
0                          ISO 3166-2:AF     .af
1                          ISO 3166-2:AX     .ax
2                          ISO 3166-2:AL     .al
3                          ISO 3166-2:DZ     .dz
4                          ISO 3166-2:AS     .as
..                                   ...     ...
266                        ISO 3166-2:WF     .wf
267                        ISO 3166-2:EH    [ap]
268                        ISO 3166-2:YE     .ye
269                        ISO 3166-2:ZM     .zm
270                        ISO 3166-2:ZW     .zw

[271 rows x 8 columns]>

In [ ]:
df.head()

  ISO 3166[1] name[5]                    Official state name[6][a]  \
  ISO 3166[1] name[5]                    Official state name[6][a]
0         Afghanistan       the Islamic Republic of Afghanistan[b]
1       Åland Islands                                  Åland[c][d]
2             Albania                      the Republic of Albania
3             Algeria  the People's Democratic Republic of Algeria
4      American Samoa                            American Samoa[c]

  Sovereignty [6][7][8] ISO 3166-1[2]                   \
  Sovereignty [6][7][8]       A-2 [5] A-3 [5] Num. [5]
0             UN member            AF     AFG      004
1               Finland            AX     ALA      248
2             UN member            AL     ALB      008
3             UN member            DZ     DZA      012
4         United States            AS     ASM      016

  ISO 3166-2[3] subdivision codes link TLD [9]
  ISO 3166-2[3] subdivision codes link TLD [9]
0                        ISO 3166-2:AF     .af
1                        ISO 3166-2:AX     .ax
2                        ISO 3166-2:AL     .al
3                        ISO 3166-2:DZ     .dz
4                        ISO 3166-2:AS     .as

In [ ]:
df.describe

<bound method NDFrame.describe of     ISO 3166[1] name[5]                       Official state name[6][a]  \
    ISO 3166[1] name[5]                       Official state name[6][a]
0           Afghanistan          the Islamic Republic of Afghanistan[b]
1         Åland Islands                                     Åland[c][d]
2               Albania                         the Republic of Albania
3               Algeria     the People's Democratic Republic of Algeria
4        American Samoa                               American Samoa[c]
..                  ...                                             ...
266   Wallis and Futuna  the Territory of the Wallis and Futuna Islands
267  Western Sahara[an]      the Sahrawi Arab Democratic Republic[c][d]
268               Yemen                           the Republic of Yemen
269              Zambia                          the Republic of Zambia
270            Zimbabwe                        the Republic of Zimbabwe

    Sovereignty [6][7][8] ISO 3166-1[2]                   \
    Sovereignty [6][7][8]       A-2 [5] A-3 [5] Num. [5]
0               UN member            AF     AFG      004
1                 Finland            AX     ALA      248
2               UN member            AL     ALB      008
3               UN member            DZ     DZA      012
4           United States            AS     ASM      016
..                    ...           ...     ...      ...
266                France            WF     WLF      876
267          Disputed[ao]            EH     ESH      732
268             UN member            YE     YEM      887
269             UN member            ZM     ZMB      894
270             UN member            ZW     ZWE      716

    ISO 3166-2[3] subdivision codes link TLD [9]
    ISO 3166-2[3] subdivision codes link TLD [9]
0                          ISO 3166-2:AF     .af
1                          ISO 3166-2:AX     .ax
2                          ISO 3166-2:AL     .al
3                          ISO 3166-2:DZ     .dz
4                          ISO 3166-2:AS     .as
..                                   ...     ...
266                        ISO 3166-2:WF     .wf
267                        ISO 3166-2:EH    [ap]
268                        ISO 3166-2:YE     .ye
269                        ISO 3166-2:ZM     .zm
270                        ISO 3166-2:ZW     .zw

[271 rows x 8 columns]>